name: Frontend CI/CD

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
      EXPO_PUBLIC_API_URL: https://photocloud.alwaysdata.net
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
          cache-dependency-path: frontend/yarn.lock

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        working-directory: frontend
        run: yarn install

      - name: Run tests
        working-directory: frontend
        run: yarn test

      - name: Debug EAS Info
        working-directory: frontend
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: eas project:info

      - name: Check project configuration
        id: check-config
        working-directory: frontend
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: |
          if eas project:info > /dev/null 2>&1; then
            echo "configured=true" >> $GITHUB_OUTPUT
          else
            echo "configured=false" >> $GITHUB_OUTPUT
            echo "EAS project not initialized or no access. Skipping update."
          fi

      # - name: Publish update
      #   if: github.event_name == 'push' && env.EXPO_TOKEN != '' && steps.check-config.outputs.configured == 'true'
      #   working-directory: frontend
      #   run: eas update --auto --branch ${{ github.ref_name }}

      - name: Build Web
        working-directory: frontend
        env:
          EXPO_PUBLIC_API_URL: ${{ env.EXPO_PUBLIC_API_URL }}
        run: npx expo export --platform web

      - name: Deploy Web to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: frontend/dist # Le dossier généré par expo export
          branch: gh-pages # La branche où le site web sera hébergé